config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'home#top'
  resource :user, only: [:new, :create, :show]
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user

    def login?
        if current_user.nil?
            redirect_to login_path, alert: "ログインしていません。"
        end
    end

    def already_login?
        unless current_user.nil?
            redirect_to user_path, notice: "既にログインしています。"
        end
    end

    def current_user
        if session[:user_id]
            current_user ||= User.find(session[:user_id])
        end
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :already_login?, except: :destroy
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] =user.id
      redirect_to user_path, notice: "ログインに成功しました。"
    else
      flash.now[:alert] = "ログインに失敗しました。"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "you have successfully logout"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :already_login?, only: [:new, :create]
  before_action :login?, only: :show

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to user_path, notice: "アカウント作成に成功しました。"
    else
      render :new
    end
  end

  def show
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<h1>Syuppy</h1>

<p>Syuppyは、出費を可視化するサービスです。</p>

<%= link_to "アカウント作成", new_user_path %>
<%= link_to "ログイン", login_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Syuppy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= notice %>
    <%= alert %>
    <div class=#container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<h1>新規登録</h1>

<%= form_with model: @user, url: user_path, local: true do |f| %>

    <div class="mb-3">
        <%= f.label :name %><br>
        <%= f.text_field :name, :placeholder => "シュッピー太郎" %>
    </div>

    <div class="mb-3">
        <%= f.label :email %><br>
        <%= f.text_field :email, :placeholder => "syuppy@taihenppy.com" %>
    </div>

    <div class="mb-3">
        <%= f.label :password %><br>
        <%= f.password_field :password %>
    </div>

    <div class="mb-3">
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation %>
    </div>

    <div>
        <%= f.submit :登録, class: "btn btn-primary mx-1" %>
    </div>
    <%= link_to "アカウントをお持ちの方はこちら", login_path %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome</h1>
<p>ようこそ "<strong><%= current_user.name %></strong>さん"</p>
<p>ログイン</p>
<%= button_to "Logout", logout_path, method: :delete %>